apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod-api-ai-dnevnik
  namespace: default # Promijenite namespace ako je drugaÄiji
spec:
  secretName: letsencrypt-prod-api-ai-dnevnik
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api-ai.dnevnik.sum.ba
  dnsNames:
    - api-ai.dnevnik.sum.ba
