apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod-api-ai-silabusi
  namespace: default # Promijenite namespace ako je drugačiji
spec:
  secretName: letsencrypt-prod-api-ai-silabusi
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api-silabusi-ai.sum.ba
  dnsNames:
    - api-silabusi-ai.sum.ba
