apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-pomocnik-ednevnik-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: public
spec:
  rules:
  - host: api-ai.dnevnik.sum.ba  # Zamijenite s vašom domenom ili koristite lokalno testiranje
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-pomocnik-ednevnik-api-service
            port:
              number: 80
  tls:
    - hosts:
        - api-ai.dnevnik.sum.ba
      secretName: letsencrypt-prod-api-ai-dnevnik